# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_symfony
    restart: always
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: cursos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
