version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony

  nginx:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
